### ISSUE TITLE
WebAssembly (WASM) support

### ISSUE THREAD

**Issue by zavalyshyn** [eclipse/paho.mqtt.rust#157]
Hi,

First of all, thanks for making this library available for Rust developers. I can successfully compile and run it on a standard Linux machine.

I wonder if there are plans for  WebAssembly support, or more specifically, `wasm32-unknown-unknown` build target. 

Right now my attempts to compile the code using paho.mqtt.rust fail because of the openssl library that fails to cross-compile for the wasm32 target. 

Any ideas on what I can try to make it work?

Thanks

Just in case I show my Cargo.toml file

```toml
[package]
name = "mqtt-example"
version = "0.1.0"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
paho-mqtt = { git = "https://github.com/eclipse/paho.mqtt.rust.git", branch = "master", features = ["vendored-ssl"]}
wasm-bindgen = "0.2"
# openssl = { version = '0.10', features = ["vendored"], optional = true }

[[bin]]
name = "sub"
path = "src/sub/subscribe_mqtt_rust.rs"

[[bin]]
name = "pub"
path = "src/pub/public_mqtt_rust.rs"
```
